name: dailymenu_app
description: "메뉴 추천 서비스 - 오늘 뭐 먹지?"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  go_router: ^14.0.0
  flutter_secure_storage: ^9.2.0
  provider: ^6.1.0
  fluttertoast: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
