spring:
  datasource:
    url: jdbc:mysql://db:3306/dailymenu?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: cache
      port: 6379

kakao:
  oauth:
    redirect-uri: http://54.204.87.58:8080/auth/kakao/callback